# Generated by Django 6.0.1 on 2026-02-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
