# Generated by Django 6.0.1 on 2026-02-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='User',
        ),
    ]
