# Generated by Django 6.0.1 on 2026-02-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0004_rename_owner_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantiy',
            field=models.IntegerField(default=1),
        ),
    ]
