# Generated by Django 6.0.1 on 2026-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0005_alter_orderitem_quantiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantiy',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
