# Generated by Django 6.0.1 on 2026-02-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0006_alter_cartitem_quantiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
